"""Generate paper assets exclusively from CoordCap evaluator output."""

from __future__ import annotations

import json
import math
from collections import Counter, defaultdict
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any


def _escape_tex(value: Any) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    return "".join(replacements.get(character, character) for character in text)


def _number(value: Any, digits: int = 3) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return "NA"
    number = float(value)
    return f"{number:.{digits}f}" if math.isfinite(number) else "NA"


def _point(cell: Mapping[str, Any], field: str) -> Any:
    metrics = cell.get("metrics")
    if not isinstance(metrics, Mapping):
        return None
    metric = metrics.get(field)
    return metric.get("point") if isinstance(metric, Mapping) else None


def _ready(bundle: Mapping[str, Any]) -> bool:
    audit = bundle.get("audit")
    return bool(isinstance(audit, Mapping) and audit.get("publication_ready") is True)


def _na_table(columns: int, label: str) -> str:
    return "\n".join(
        [
            "% AUTO-GENERATED by CoordCap; empirical matrix is not publication-ready.",
            r"\begin{tabular}{" + "l" * columns + "}",
            r"\hline",
            rf"\multicolumn{{{columns}}}{{c}}{{NA -- INCOMPLETE: {_escape_tex(label)}}} \\",
            r"\hline",
            r"\end{tabular}",
            "",
        ]
    )


def _paper_table(tabular: str, *, ready: bool) -> str:
    caption = (
        "Primary formal CoordCap metrics. Every value is generated from the complete "
        "expected-run matrix."
        if ready
        else "Formal matrix status. No empirical value is exposed before the frozen matrix is complete."
    )
    return "\n".join(
        [
            "% AUTO-GENERATED; do not edit empirical values by hand.",
            r"\begin{table*}[t]",
            r"\centering",
            r"\small",
            tabular.rstrip(),
            rf"\caption{{{caption}}}",
            r"\label{tab:overall}",
            r"\end{table*}",
            "",
        ]
    )


def write_tables(bundle: Mapping[str, Any], results_root: str | Path) -> dict[str, Path]:
    root = Path(results_root)
    table_root = root / "tables"
    table_root.mkdir(parents=True, exist_ok=True)
    primary_path = table_root / "table_primary_metrics.tex"
    overall_path = table_root / "overall_results.tex"
    capacity_path = table_root / "table_coordination_capacity.tex"
    consistency_path = table_root / "table_coordination_consistency.tex"
    macros_path = table_root / "coordcap_metrics.tex"

    if not _ready(bundle):
        primary_text = _na_table(8, "formal expected-run matrix incomplete")
        primary_path.write_text(primary_text, encoding="utf-8")
        overall_path.write_text(_paper_table(primary_text, ready=False), encoding="utf-8")
        capacity_path.write_text(_na_table(7, "capacity unavailable"), encoding="utf-8")
        consistency_path.write_text(_na_table(3, "permutation panel unavailable"), encoding="utf-8")
        macros_path.write_text(
            "% AUTO-GENERATED; do not replace NA by hand.\n"
            r"\newcommand{\CoordCapResultsReady}{0}" "\n"
            r"\newcommand{\CoordCapExpectedRuns}{NA}" "\n"
            r"\newcommand{\CoordCapScoredRuns}{NA}" "\n",
            encoding="utf-8",
        )
        return {
            "primary_table": primary_path,
            "overall_table": overall_path,
            "capacity_table": capacity_path,
            "consistency_table": consistency_path,
            "macros": macros_path,
        }

    metrics = bundle.get("metrics") if isinstance(bundle.get("metrics"), Mapping) else {}
    headline = metrics.get("headline_cells") if isinstance(metrics, Mapping) else []
    lines = [
        "% AUTO-GENERATED from complete formal evaluator output.",
        r"\begin{tabular}{llrrrrrr}",
        r"\hline",
        r"Model & Method & JSR & HCVR & Mean regret & Worst regret & Pareto & JSON valid \\",
        r"\hline",
    ]
    for cell in headline if isinstance(headline, list) else []:
        lines.append(
            " & ".join(
                [
                    _escape_tex(cell.get("model")),
                    _escape_tex(cell.get("method")),
                    _number(_point(cell, "joint_success")),
                    _number(_point(cell, "hard_constraint_violation")),
                    _number(_point(cell, "mean_principal_regret")),
                    _number(_point(cell, "worst_principal_regret")),
                    _number(_point(cell, "pareto_efficient")),
                    _number(_point(cell, "initial_json_valid")),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\hline", r"\end{tabular}", ""])
    primary_text = "\n".join(lines)
    primary_path.write_text(primary_text, encoding="utf-8")
    overall_path.write_text(_paper_table(primary_text, ready=True), encoding="utf-8")

    capacity_lines = [
        "% AUTO-GENERATED from frozen point-and-bound gates.",
        r"\begin{tabular}{llllrrl}",
        r"\hline",
        r"Model & Method & Conflict & Tokens & Calls & Capacity & Gate \\",
        r"\hline",
    ]
    capacity = bundle.get("capacity")
    for row in capacity if isinstance(capacity, list) else []:
        capacity_lines.append(
            " & ".join(
                [
                    _escape_tex(row.get("model")),
                    _escape_tex(row.get("method")),
                    _escape_tex(row.get("conflict_level")),
                    _escape_tex(row.get("max_answer_tokens")),
                    _escape_tex(row.get("max_model_calls")),
                    _escape_tex(row.get("capacity_label")),
                    "point+95\\% CI",
                ]
            )
            + r" \\"
        )
    capacity_lines.extend([r"\hline", r"\end{tabular}", ""])
    capacity_path.write_text("\n".join(capacity_lines), encoding="utf-8")

    consistency = metrics.get("coordination_consistency") if isinstance(metrics, Mapping) else {}
    consistency_lines = [
        "% AUTO-GENERATED from the frozen permutation panel.",
        r"\begin{tabular}{rrr}",
        r"\hline",
        r"Pairs & Consistent & Rate \\",
        r"\hline",
        f"{_escape_tex(consistency.get('pair_count'))} & "
        f"{_escape_tex(consistency.get('consistent_pairs'))} & "
        f"{_number(consistency.get('rate'))} " + r"\\",
        r"\hline",
        r"\end{tabular}",
        "",
    ]
    consistency_path.write_text("\n".join(consistency_lines), encoding="utf-8")

    audit = bundle["audit"]
    macros_path.write_text(
        "% AUTO-GENERATED from evaluator output.\n"
        r"\newcommand{\CoordCapResultsReady}{1}" "\n"
        rf"\newcommand{{\CoordCapExpectedRuns}}{{{int(audit['expected_runs'])}}}" "\n"
        rf"\newcommand{{\CoordCapScoredRuns}}{{{int(audit['scored_runs'])}}}" "\n"
        rf"\newcommand{{\CoordCapConsistencyRate}}{{{_number(consistency.get('rate'))}}}" "\n",
        encoding="utf-8",
    )
    return {
        "primary_table": primary_path,
        "overall_table": overall_path,
        "capacity_table": capacity_path,
        "consistency_table": consistency_path,
        "macros": macros_path,
    }


def _matplotlib():
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def _save_pdf(fig: Any, path: Path) -> None:
    fig.savefig(
        path,
        format="pdf",
        bbox_inches="tight",
        metadata={"Creator": "CoordCap", "CreationDate": None, "ModDate": None},
    )


def _placeholder_pdf(path: Path, title: str, bundle: Mapping[str, Any]) -> None:
    plt = _matplotlib()
    fig, axis = plt.subplots(figsize=(7.2, 4.2))
    axis.axis("off")
    audit = bundle.get("audit") if isinstance(bundle.get("audit"), Mapping) else {}
    detail = (
        f"Expected: {audit.get('expected_runs', 'NA')}   "
        f"Missing: {audit.get('missing_runs', 'NA')}   "
        f"Duplicates: {audit.get('duplicate_runs', 'NA')}"
    )
    axis.text(0.5, 0.62, title, ha="center", va="center", fontsize=16, weight="bold")
    axis.text(
        0.5,
        0.43,
        "INCOMPLETE - no publishable formal matrix",
        ha="center",
        va="center",
        fontsize=13,
        color="#9b2c2c",
    )
    axis.text(0.5, 0.30, detail, ha="center", va="center", fontsize=10)
    _save_pdf(fig, path)
    plt.close(fig)


def write_figures(bundle: Mapping[str, Any], results_root: str | Path) -> dict[str, Path]:
    root = Path(results_root)
    figure_root = root / "figures"
    figure_root.mkdir(parents=True, exist_ok=True)
    performance_path = figure_root / "performance_by_principal_count.pdf"
    capacity_path = figure_root / "coordination_capacity.pdf"
    failures_path = figure_root / "failure_modes.pdf"
    paths = {
        "performance_figure": performance_path,
        "capacity_figure": capacity_path,
        "failure_figure": failures_path,
    }
    if not _ready(bundle):
        for label, path in (
            ("Performance by principal count", performance_path),
            ("Coordination capacity", capacity_path),
            ("Failure modes", failures_path),
        ):
            _placeholder_pdf(path, label, bundle)
        return paths

    plt = _matplotlib()
    rows = [
        row
        for row in bundle.get("scored_runs", [])
        if isinstance(row, Mapping) and row.get("order_variant") == "canonical"
    ]
    by_count: dict[int, list[Mapping[str, Any]]] = defaultdict(list)
    for row in rows:
        if isinstance(row.get("principal_count"), int):
            by_count[int(row["principal_count"])].append(row)
    counts = sorted(by_count)

    def mean(field: str, selected: Sequence[Mapping[str, Any]]) -> float:
        values = [float(row[field]) for row in selected]
        return sum(values) / len(values)

    fig, axis = plt.subplots(figsize=(7.2, 4.4))
    axis.plot(counts, [mean("joint_success", by_count[n]) for n in counts], marker="o", label="Joint success")
    axis.plot(
        counts,
        [mean("hard_constraint_violation", by_count[n]) for n in counts],
        marker="s",
        label="Hard violation",
    )
    axis.plot(
        counts,
        [mean("worst_principal_regret", by_count[n]) for n in counts],
        marker="^",
        label="Worst-principal regret",
    )
    axis.set_xlabel("Principal count")
    axis.set_ylabel("Rate / regret")
    axis.set_ylim(-0.02, 1.02)
    axis.grid(alpha=0.25)
    axis.legend(frameon=False)
    fig.tight_layout()
    _save_pdf(fig, performance_path)
    plt.close(fig)

    capacity_rows = [row for row in bundle.get("capacity", []) if isinstance(row, Mapping)]
    methods = sorted({str(row.get("method")) for row in capacity_rows})
    values = [
        [float(row["capacity"]) if row.get("capacity") is not None else 1.5 for row in capacity_rows if row.get("method") == method]
        for method in methods
    ]
    fig, axis = plt.subplots(figsize=(7.2, 4.4))
    if methods and all(values):
        axis.boxplot(values, tick_labels=methods, showmeans=True)
        axis.set_ylabel("Capacity (<2 encoded at 1.5)")
        axis.tick_params(axis="x", rotation=20)
        axis.grid(axis="y", alpha=0.25)
    else:
        axis.axis("off")
        axis.text(0.5, 0.5, "Capacity unavailable", ha="center", va="center")
    fig.tight_layout()
    _save_pdf(fig, capacity_path)
    plt.close(fig)

    failure_counts = Counter(
        str(row.get("failure_category")) for row in rows if row.get("failure_category") != "success"
    )
    labels = sorted(failure_counts)
    fig, axis = plt.subplots(figsize=(7.2, 4.4))
    if labels:
        axis.barh(labels, [failure_counts[label] for label in labels], color="#4c78a8")
        axis.set_xlabel("Expected-run count")
        axis.grid(axis="x", alpha=0.25)
    else:
        axis.axis("off")
        axis.text(0.5, 0.5, "No categorized failures", ha="center", va="center")
    fig.tight_layout()
    _save_pdf(fig, failures_path)
    plt.close(fig)
    return paths


def write_fact_sheet(bundle: Mapping[str, Any], results_root: str | Path) -> dict[str, Path]:
    root = Path(results_root)
    root.mkdir(parents=True, exist_ok=True)
    fact_path = root / "experiment_fact_sheet.md"
    audit_path = root / "execution_audit.md"
    failures_path = root / "failure_examples.json"
    audit = bundle.get("audit") if isinstance(bundle.get("audit"), Mapping) else {}
    ready = _ready(bundle)
    fact_lines = [
        "# CoordCap Experiment Fact Sheet",
        "",
        f"- Protocol: `{bundle.get('protocol_version', 'NA')}`",
        f"- Execution config SHA-256: `{bundle.get('execution_config_sha256', 'NA')}`",
        f"- Split: `{bundle.get('split', 'NA')}`",
        f"- Expected runs: {audit.get('expected_runs', 'NA')}",
        f"- Scored runs: {audit.get('scored_runs', 'NA')}",
        f"- Matrix complete: `{str(bool(audit.get('matrix_complete'))).lower()}`",
        f"- Publication ready: `{str(ready).lower()}`",
        f"- Missing / duplicate: {audit.get('missing_runs', 'NA')} / {audit.get('duplicate_runs', 'NA')}",
        "",
    ]
    if ready:
        fact_lines.append("All empirical values in the generated tables and figures come from this complete evaluator bundle.")
    else:
        fact_lines.append("**INCOMPLETE:** empirical metrics are not eligible for paper claims; generated paper assets display NA.")
    fact_path.write_text("\n".join(fact_lines) + "\n", encoding="utf-8")

    audit_lines = ["# CoordCap Execution Audit", ""]
    for key, value in sorted(audit.items()):
        if key in {"status_counts", "failure_counts"}:
            audit_lines.extend([f"## {key.replace('_', ' ').title()}", ""])
            if isinstance(value, Mapping):
                audit_lines.extend(f"- `{name}`: {count}" for name, count in sorted(value.items()))
            audit_lines.append("")
        elif not isinstance(value, (dict, list)):
            audit_lines.append(f"- `{key}`: `{value}`")
    audit_path.write_text("\n".join(audit_lines) + "\n", encoding="utf-8")
    failures_path.write_text(
        json.dumps(bundle.get("failure_examples", []), ensure_ascii=False, indent=2, sort_keys=True)
        + "\n",
        encoding="utf-8",
    )
    return {"fact_sheet": fact_path, "execution_audit": audit_path, "failure_examples": failures_path}


def write_paper_macros(
    bundle: Mapping[str, Any],
    results_root: str | Path,
    *,
    paper_root: str | Path | None = None,
) -> dict[str, Path]:
    """Write the macros imported unconditionally by ``paper/main.tex``."""

    results = Path(results_root)
    paper = Path(paper_root) if paper_root is not None else results.parent / "paper"
    paper.mkdir(parents=True, exist_ok=True)
    output = paper / "generated_results.tex"
    if not _ready(bundle):
        text = "\n".join(
            [
                "% AUTO-GENERATED. Incomplete formal evaluations must remain non-numeric.",
                r"\providecommand{\ResultStatus}{PENDING}",
                r"\providecommand{\FormalRunCount}{NA}",
                r"\providecommand{\FormalExpectedCount}{NA}",
                r"\providecommand{\EmpiricalSummarySentence}{The frozen formal matrix is incomplete; no empirical performance claim is available.}",
                r"\providecommand{\FailureSummarySentence}{Formal failure diagnostics remain pending until the complete expected-run matrix is attributable.}",
                "",
            ]
        )
    else:
        audit = bundle.get("audit") if isinstance(bundle.get("audit"), Mapping) else {}
        scope = audit.get("frozen_scope") if isinstance(audit.get("frozen_scope"), Mapping) else {}
        variants = scope.get("order_variant_counts") if isinstance(scope.get("order_variant_counts"), Mapping) else {}
        canonical_count = int(variants.get("canonical", 0))
        failure_counts = audit.get("failure_counts") if isinstance(audit.get("failure_counts"), Mapping) else {}
        failures = {str(key): int(value) for key, value in failure_counts.items() if key != "success"}
        if failures:
            category, count = sorted(failures.items(), key=lambda item: (-item[1], item[0]))[0]
            failure_sentence = (
                f"The most frequent generated diagnostic category is {_escape_tex(category)} "
                f"({_escape_tex(count)} expected runs)."
            )
        else:
            failure_sentence = "The evaluator assigned no non-success diagnostic category."
        text = "\n".join(
            [
                "% AUTO-GENERATED from a complete, independently recomputed formal matrix.",
                r"\providecommand{\ResultStatus}{COMPLETE}",
                rf"\providecommand{{\FormalRunCount}}{{{canonical_count:,}}}",
                rf"\providecommand{{\FormalExpectedCount}}{{{canonical_count:,}}}",
                r"\providecommand{\EmpiricalSummarySentence}{The complete formal matrix has passed expected-ledger and independent-oracle recomputation gates; all empirical values are data-derived.}",
                rf"\providecommand{{\FailureSummarySentence}}{{{failure_sentence}}}",
                "",
            ]
        )
    output.write_text(text, encoding="utf-8")
    return {"paper_macros": output}


def build_paper_assets(
    bundle: Mapping[str, Any],
    results_root: str | Path,
    *,
    paper_root: str | Path | None = None,
) -> dict[str, Path]:
    paths: dict[str, Path] = {}
    paths.update(write_tables(bundle, results_root))
    paths.update(write_figures(bundle, results_root))
    paths.update(write_fact_sheet(bundle, results_root))
    paths.update(write_paper_macros(bundle, results_root, paper_root=paper_root))
    return paths
